### ISSUE TITLE
TUITableView cell queue fix

### ISSUE THREAD

**Issue by avaidyam** [twitter-archive/twui#102]
EDIT: The code I posted previously really did not fix anything. It was a placebo :[
The question that remains is that the -reloadData call ends up jumbling up all the cells and in my use-case, the table view becomes really unusable. What am I missing here/what is going wrong? What needs to be fixed?

**Comment by joshaber** [comment]
We talked this over via email. There's no bug, just a misunderstanding.

**Comment by avaidyam** [comment]
Yep, sorry bout that, didn't close the issue :]
