### ISSUE TITLE
TUIImage for animated gif?

### ISSUE THREAD

**Issue by devon** [twitter-archive/twui#104]
Any idea how to do this? Thank you.

**Comment by avaidyam** [comment]
Something like this: http://iphonedevelopertips.com/graphics/animated-gif-animated-images-iphone-style.html would help, seeing as both TUIImage and UIImage are just CGImageRef wrappers.

**Comment by devon** [comment]
Thanks. 

I got the each frame fro NSBitmapImageRep *rep = [[_img representations] objectAtIndex:0];

and duration:
CGFloat frame_times = [[rep valueForProperty:NSImageCurrentFrameDuration] floatValue];

Use animation to play the gif. It works.

**Comment by avaidyam** [comment]
Welcome!
