### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by agborkowski** [twitter-archive/twui#110]
/Users/nim/Sites/lib/twui/lib/UIKit/TUINSView.m

[self _updateLayerScaleFactor];
Receiver type 'TUINSView' for instance message does not declare a method with selector '_updateLayerScaleFactor'

[self _updateLayerScaleFactor];
Receiver type 'TUINSView' for instance message does not declare a method with selector '_updateLayerScaleFactor'

**Comment by joshaber** [comment]
It sounds like you need to use a newer version of Xcode. Or you can work around it by declaring `-(void)_updateLayerScaleFactor;` in the `TUINSView` interface.

**Comment by agborkowski** [comment]
yes u right. thanx
