### ISSUE TITLE
Goal of twui ?

### ISSUE THREAD

**Issue by ujjwalt** [twitter-archive/twui#117]
After going through the structure of the code as well as the little documentation provided - I'm still left confused as to **_what is the goal of this entire project ?**_
# What does twui wish to achieve/solve ?
1. Does it wish to be an _independent_ UI framework with zero dependencies on AppKit and only using some lower level apis and the foundation framework ?
2. Why does it wish to be _compatible_ with AppKit and to achieve intermixing of TUIViews and NSViews ! This is an unrealistic goal to aim for considering that AppKit is closed source. Only one way communication can be established in this form. Two way communication is also possible but somewhat _hacky_ !
3. Does it only wish to add a _custom look_ and new views utilising _core animation_ for blazing fast rendering ?

**Comment by avaidyam** [comment]
To be the best damned Core Animation Layer-based graphics interface kit. Evarr. With two 'r's.
1. It is indeed independent, however, used sparingly, can coexist with AppKit, and perhaps even Chameleon. 
2. It does NOT wish to be compatible- the TUINSView is the host layer for the Core Animation TUIView system, which passes events for handling to all the subviews in a responder chain.
3. It DOES let you do this, but it's not a _custom_ look, per se, as there is no look or feel at the moment (customize it!).

**Comment by jspahrsummers** [comment]
Regarding item 2, part of [our](https://github.com/bitswift) goal with the [Velvet framework](https://github.com/bitswift/Velvet) was to support just this. We have a custom [TwUI fork](https://github.com/bitswift/twui) which allows two-way bridging between AppKit and Velvet, and Velvet and TwUI.
