### ISSUE TITLE
UIKit / iOS support?

### ISSUE THREAD

**Issue by adib** [twitter-archive/twui#120]
Hi,

Any plans for making TwUI workable on iOS (UIKit ?) 

What are the areas that needs adapting?
- NSResponder --> UIResponder
- coordinate systems
- what else?

Thanks

**Comment by joshaber** [comment]
No. TwUI exists to fill a gap on Mac as a layer-based, modern UI framework. In iOS, UIKit is already mostly that.

**Comment by joshaber** [comment]
Oh I should also note. If your goal is easy iOS <=> Mac porting, [Chameleon](https://github.com/BigZaphod/Chameleon) is probably more up your alley.

**Comment by adib** [comment]
@joshaber Yeah, I've been pondering between TwUI and Chameleon. It's for a new app for the Mac with planned subsequent iOS release, so there's no "legacy" UIKit code so far, so straight UIKit compatibility isn't much needed at this point. Although it would be nice if there is a framework that can facilitate more code sharing among the two editions of the app.

One of my hesitations with Chameleon is the "spotty" UIKit implementations (i.e., a lot of classes aren't there and there isn't much guideline which one are working) and the workarounds that they had to make to implement UIKit properly on the Mac. Since UIKit emulation is an unneeded baggage, I thought maybe TwUI will be more adaptable. 

Just for the sake of the discussion, what would it take to run TwUI on iOS? (let's say, version 5.1).

**Comment by joshaber** [comment]
> Just for the sake of the discussion, what would it take to run TwUI on iOS? (let's say, version 5.1).

@adib I'll be honest, I'm not really sure :) All the event routing would have to change, obviously. Other that that, it might be pretty straightforward NS => UI.

**Comment by avaidyam** [comment]
Oh, hi there! My private fork is about 90% compatible with iOS, I've been dragging, dropping, and renaming and it works fine, but other than that, TwUI is a genuine Core Animation experience for Mac, not iOS.

**Comment by adib** [comment]
Cool! Any plans to make your fork public?

Btw, what do you really mean by "experience for Mac OS, not iOS"? Is it Mouseovers?

Thank you

---

Sasmito Adibowo
http://cutecoder.org

**Comment by avaidyam** [comment]
Oh, i've got a fork of it going and i'm committing slowly to that fork. I've also been working on slowly getting it to merge with the github/dev fork too (if that ever happens xD)

I meant the 'experience of using' such a Core Animation powered engine for UI, much like iOS, but for Mac developers.
