### ISSUE TITLE
TUILabel - jagged text when background color is clearColor

### ISSUE THREAD

**Issue by gcox** [twitter-archive/twui#129]
When a TUILabel's background color is set to clearColor the text that renders is jagged and ugly, the text looks perfect with any other background color.  Is it known problem? Any workaround?

I have tried setting it's opaque property to NO but it doesn't affect the rendered text.

**Comment by dannygreg** [comment]
This is due to a lack of sub-pixel anti aliasing and a known problem for Core Animation (although this was fixed in 10.8). Have a look at `TUITextRenderer` as it is more likely what you want to be using in this case.

**Comment by gcox** [comment]
I see, I was under the impression that TUI controls dealt with this issue by using TUITextRenderer internally, is it safe to assume that all TUI controls will behave this way in 10.7?

**Comment by dannygreg** [comment]
They do use `TUITextRenderer`… it's just impossible to draw text onto a clear background and have SPAA work. Hence `TUILabel` suffers.
