### ISSUE TITLE
TWUIColor – Components

### ISSUE THREAD

**Issue by alexzielenski** [twitter-archive/twui#2]
I think in TWUIColor it'd be useful to have methods such as - redComponent, -blueComponent, -greenComponent, etc. And rename -alpha to -alphaComponent

**Comment by indragiek** [comment]
You could always just get the `CGColorRef` for the `TUIColor` and grab the components from there.

**Comment by alexzielenski** [comment]
That would be a bit redundant since this is already just an objective-c wrapper around CGColorRef and that would be what those methods would do.

**Comment by lorenbrichter** [comment]
what's the fastest way to determine if a given cgcolorref is rgba?

**Comment by lorenbrichter** [comment]
I think this would be best server with a single method
- (void)getRed:(float *)r green:(float *)g blue:(float *)b alpha:(float *)a;

like NSColor - and would prevent the temptation to call multiple [color xxxComponent] methods back to back (which would be slower than this single multi-getter).  It would be the caller's responsibility to ensure that the receiver is an RGBA color, and the only sanity check would be to confirm that the # of components == 4 (which is really fast).

**Comment by lorenbrichter** [comment]
pushed getters for RGBA and LA (and renamed -alpha -> -alphaComponent to match NSColor)

**Comment by alexzielenski** [comment]
Thanks!
