### ISSUE TITLE
Should right mouse click on table view select the cell?

### ISSUE THREAD

**Issue by brutella** [twitter-archive/twui#37]
The right mouse click events are mostly used to show context menus based on underlying cell. Therefore I think the cell should also be selected when right clicking on the cell. 

In the current implementation the cell is only selected when left clicking on the cell.

**Comment by Naituw** [comment]
You can make it a optional delegate method

**Comment by brutella** [comment]
Right, would be a nice solution!

**Comment by lorenbrichter** [comment]
works for me, but one change - method should be of the form: -(BOOL)tableViewShouldSelectRowOnRightClick:(TUITableView *)tableView;

**Comment by omz** [comment]
I think it would be even better if the delegate method also included the indexPath that is about to be selected. It might be desirable to have a different behavior for different rows.

**Comment by lorenbrichter** [comment]
Totally.

**Comment by brutella** [comment]
We could make a more generic method where a selection can be restricted based on the event. 

For example: `- (BOOL)tableView:(TUITableView*)tableView shouldSelectRowAtIndexPath:(TUIFastIndexPath*)indexPath forEvent:(NSEvent*)event;`

**Comment by lorenbrichter** [comment]
Sweet, yeah.

**Comment by brutella** [comment]
Pull request #38 merged. Done!
