### ISSUE TITLE
TUITableView resizing issue

### ISSUE THREAD

**Issue by brutella** [twitter-archive/twui#52]
There seems to be a problem when resizing a window with a containing TUITableView.

I couldn't find the corresponding code, which produces the error - maybe someone else finds it ;)

![TUITableView from Example project](http://dl.dropbox.com/u/2187517/twui_tuitableview.png)

**Comment by choco** [comment]
I've been searching for the responsible good for like an hour and found nothing.... Anyone had better luck?
It seems that when the window gets resized the layer does't correctly update(?!?!?) during the scroll.....

**Comment by bww** [comment]
Pull #63 fixes this problem.

**Comment by brutella** [comment]
Works awesome!
