### ISSUE TITLE
How to create a link in TUIAttributedString?

### ISSUE THREAD

**Issue by mrjjwright** [twitter-archive/twui#60]
I was wondering how to detect click on a hyperlinkTUIAttributedString created as below.   The event mouseDown is not registering on the associated TUITextRenderer.  Is there a better way to create links in TUITextRenderers?  

Thanks!

John

```
  +(id)hyperlinkFromString:(NSString*)inString withURL:(NSURL*)aURL
  {
      TUIAttributedString* attrString = [TUIAttributedString stringWithString:inString];
      NSRange range = NSMakeRange(0, [attrString length]);

      [attrString beginEditing];
      [attrString addAttribute:NSLinkAttributeName value:[aURL absoluteString] range:range];

      // make the text appear in blue
      NSColor *blueColor = [TUIColor colorWithHexString:@"#3B5998"].nsColor;
      [attrString addAttribute:NSForegroundColorAttributeName value:blueColor range:range];

      [attrString endEditing];

      return attrString;
  }
```

**Comment by choco** [comment]
Why the mouseDown event isn't registering ? Have you added your TUITextRenderer to the view text renders  array? If you don't do this the event won't propagate ( i think, I''m not sure).

**Comment by mrjjwright** [comment]
Yes, I did add this to the `textRenderers` array.   My normal text registers but not the links.  I will keep trying, I am probably doing something silly.

**Comment by Naituw** [comment]
atebits said 19 days ago to me  ;P :
Check out the delegate methods for TUITextRenderer, you have your delegate supply the ranges that should be clickable, and in your -mouseUp: method (in your view), you can determine the clicked range with the .hitRange property on the text renderer.

this solve my problem, and it is a faster way if you dynamical create AttributedString when you scroll the tableView.

**Comment by mrjjwright** [comment]
Sweet, so I will just not use 'NSLinkAttribute' and just use clickable ranges.

**Comment by mrjjwright** [comment]
I solved this by subclassing TUITextRenderer and overriding mouseUp as so:

```
- (void)mouseUp:(NSEvent *)event {
    CFIndex i = [self stringIndexForEvent:event];
    NSRange effectiveRange = NSMakeRange(0, 0);
    // Get the attributed string in this index
    id attr = [attributedString attribute:NSLinkAttributeName atIndex:i effectiveRange:&effectiveRange];
    if (attr && [attr isKindOfClass:[NSURL class]]) {
        //Open up the url
        [[NSWorkspace sharedWorkspace] openURL:attr];
    }
    [super mouseUp:event];
}
```

I will add on code to handle other types of attributes as well specific to my app.  Thanks!
