### ISSUE TITLE
TUIView Animation Problem

### ISSUE THREAD

**Issue by Naituw** [twitter-archive/twui#67]
I'm writing  a navigation controller based on twui,

and I'm trying to make a animation like iOS when the navigation controller push new view.

In the pushViewController: method, follow things will be done:
1.insert new view to index 0;
2.set new view's start frame;
3.animate old view and new view to destination frame.

here is a sample project:
https://github.com/Naituw/TUIViewAnimationDemo

when I click push button, old view's animation works fine,
but , the new view doesn't make any animation, it just jump to the destination frame.

Did I missed anything?

**Comment by joshaber** [comment]
I have an example project that does just that: https://github.com/joshaber/TwUIPushPopTest.

Note specifically this bit in `PPNavigationController`:

``` objc
// We need to force a flush so that the view's frame is set to the far right before we animate. Otherwise CA will put this off until the end of the runloop and won't bother animating.
[CATransaction begin];
viewController.view.frame = CGRectMake(self.view.bounds.size.width, 0.0f, viewController.view.bounds.size.width, viewController.view.bounds.size.height);
[CATransaction flush];
[CATransaction commit];
```

**Comment by Naituw** [comment]
Awesome! After add those three lines, my problem solved, Thanks a lot!~
