### ISSUE TITLE
Default backgroundColor for TUIImageView

### ISSUE THREAD

**Issue by zhangchn** [twitter-archive/twui#69]
I drew an icon on CGBitmapContextCreate with CoreGraphics and assigned it to a TUIImageView. That icon was designed to be clipped as RoundRect, but what I got was a round-rect-ed icon with black corners.

After a few tries, it would not work until the backgroundColor of TUIImageView was set to clear color.

It seems that the default backgroundColor was nil for both TUIImageView and TUIView(, correct me if I am wrong). Is this an issue?

**Comment by lorenbrichter** [comment]
Setting TUIImageView's backgroundColor to clear has a side-effect of marking it as non-opaque, which may slow things down.  I'm OK with putting the burden on the programmer to be explicit about which views they want to be blended.
