### ISSUE TITLE
TUITextRenderer Break modes with multiple lines

### ISSUE THREAD

**Issue by erndev** [twitter-archive/twui#70]
When lineBreakMode is set for the renderer, it seems to behave differently when the frame allows drawing multiple lines of the text.
For a frame that can contain multiple lines, if the text renderer properties are set like  this: 

```
[textRedender setAlignment:TUITextAlignmentLeft lineBreakMode:TUILineBreakModeWordWrap];
```

Multiple lines are drawn, the last line is wrapped to the last word, and the ellipsis is not drawn as expected.

But it i change the properties to this:

```
[textRedender setAlignment:TUITextAlignmentLeft lineBreakMode:TUILineBreakModeWordWrap | TUILineBreakModeTailTruncation];
```

then the ellipsis is shown at the end, but only the first line is drawn. The rest of the lines are not drawn by the renderer.

EDIT: Added screenshot

![screenshot](http://i55.tinypic.com/34dodpc.png)

The upper part has been drawn without TUILineBreakModeTailTruncation. It shows both lines. The lower part was drawn with that option added, and in this case, the second line is not drawn. The frame size is the same in both cases.

**Comment by lorenbrichter** [comment]
Is this a TUITextRenderer issue or a Core Text issue?  (I've never tried doing ellipsis with multiple lines of text).  Does Core Text support that?

**Comment by erndev** [comment]
Well, searching a bit about it,  it seems that's the expected behavior of CoreText. I was expecting it to behave in a similar way as "Truncate last visible line" in NSTextfield, or the parameter NSStringDrawingTruncatesLastVisibleLine of NSAttributtedString. It seems that the text must be drawn line by line to achieve that.

After further reading, it's definitely how CoreText works, so  i am closing the issue.
