### ISSUE TITLE
Apple Mach-O Linker (Ld) Warning when using Xcode 4.2 OS X 10.7.2

### ISSUE THREAD

**Issue by stoneros** [twitter-archive/twui#77]
Ld /Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Products/Debug/Example.app/Contents/MacOS/Example normal x86_64
    cd /Volumes/Data/stoneros/Desktop/twitter-twui-a302717/ExampleProject
    setenv MACOSX_DEPLOYMENT_TARGET 10.6
    /Developer/usr/bin/clang -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.7.sdk -L/Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Products/Debug -F/Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Products/Debug -filelist /Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Intermediates/Example.build/Debug/Example.build/Objects-normal/x86_64/Example.LinkFileList -mmacosx-version-min=10.6 -framework QuartzCore -framework ApplicationServices -framework Cocoa -o /Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Products/Debug/Example.app/Contents/MacOS/Example

ld: warning: instance method 'setDrawRect:' in category from /Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Intermediates/Example.build/Debug/Example.build/Objects-normal/x86_64/TUIView.o overrides method from class in /Volumes/Data/stoneros/Library/Developer/Xcode/DerivedData/Example-hafykyiiqnbqvifyltzchgxygaol/Build/Intermediates/Example.build/Debug/Example.build/Objects-normal/x86_64/TUIView.o

**Comment by RSully** [comment]
Noticing same issue in my project, Xcode 4.2 on 10.7 building for 64bit (with and without NS_BUILD_32_LIKE_64 flag). I just looked through TUIView and couldn't see anything obvious

**Comment by joshaber** [comment]
I have this fixed in my fork: https://github.com/joshaber/twui/commit/16b7d203f50b72ff31fcd86e9bc1551e6a9bafce

**Comment by stoneros** [comment]
thanks Josh,it's work
