### ISSUE TITLE
EXC_BAD_ACCESS in demo App using keyboard

### ISSUE THREAD

**Issue by erndev** [twitter-archive/twui#80]
I am getting a crash in the demo app when the keyboard is used to navigate the tableview.

These are the steps to reproduce it:
1. In the test app, Scroll down to the last row of the table (using mouse or keyboard)
2. Click on any row to select it.
3. Keep pressing up & down keys to change the selected row. Eventually,  an EXC_BAD_ACCESS in cellForRowAtIndexPath of TUITableview.m.  The section number in the indexPath parameter seem to have an abnormally high value. section=10376293541730151571 , but the row number seems OK.

EDIT: After some more tests, it seems that in step 1 it's not needed to go to the end of the table.
just clicking a row in a section different to the first one, can cause the crash.

EDIT2: It seems that the problem happens only with current version in github. If i rollback to the previous version (without this [commit](https://github.com/twitter/twui/commit/a555cd84e746df5afb3358f23a1b791c24c186bd) ) it works fine.
It seems the problem is in the function - (void)selectRowAtIndexPath:(TUIFastIndexPath *)indexPath animated:(BOOL)animated scrollPosition:(TUITableViewScrollPosition)scrollPosition  , and with the "oldIndexPath". 
If i revert that function to the code before the commit, they keyboard works fine and it does not crash.

**Comment by cherifya** [comment]
I'm getting the same exception. I will try your workaround and see if it works. Thanks.

**Comment by cherifya** [comment]
Workaround works great. Thanks.
Commit mentionned above was a merge of pull request #74. The pull request needs to be reviewed apparently.
