### ISSUE TITLE
Using TUITableView on Lion prints error to Console

### ISSUE THREAD

**Issue by brutella** [twitter-archive/twui#93]
Getting the following message when using a TUIScrollView on Lion (10.7)
`-_scrollPhase is deprecated for NSScrollWheel. Please use -momentumPhase.`

**Comment by joshaber** [comment]
`TUIKit.m` defines two global variables you need to set for TwUI to behave right: `Screen_Scale` and `AtLeastLion`. Check out the example project's `main.m` to see how and when they should be set.

**Comment by brutella** [comment]
Thanks, this also fixes a scrolling issue!
