### ISSUE TITLE
Needed: TUINavigationController

### ISSUE THREAD

**Issue by mrjjwright** [twitter-archive/twui#95]
I need a UINavigationController like component for my app and was wondering if anybody has already built one they would like to share.  If not I plan to take some inspiration from Chameleon and build one myself.  

Thanks!

**Comment by saidmarouf** [comment]
I would look at https://github.com/joshaber/TwUIPushPopTest. I have a simple implementation inspired by this, but not as sophisticated as UINavigationController. Will try to post it when I get to polishing it.

**Comment by jparishy** [comment]
I have started writing a TUINavigationController class with UINavigationController as a model, but it's still early. I should have time to work on it this week end and merge the early work in my fork

**Comment by mrjjwright** [comment]
Thanks guys.  jparishy, I will watch your fork and maybe I can contribue.  I didn't know about TwUIPushPopTest either.
